name: Update Sophos Blocklist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 14:00 Latvia time (UTC+2)

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old blocklist file
        run: |
          if [ -f sophos_web_blocklist.txt ]; then
            rm sophos_web_blocklist.txt
            echo "Old blocklist file removed"
          else
            echo "No existing blocklist file found"
          fi

      - name: Download and process host file
        run: |
          # Download source file
          curl -sSL https://raw.githubusercontent.com/neodevpro/neodevhost/master/host -o raw_host
          
          # Process file: remove comments, empty lines, prefixes, duplicates, and sort
          grep -v '^#' raw_host | \
          grep -v '^$' | \
          sed 's/^0\.0\.0\.0 //' | \
          sed 's/^127\.0\.0\.1 //' | \
          grep -v '^localhost$' | \
          grep -v '^broadcasthost$' | \
          sort -u > sophos_web_blocklist.txt
          
          # Remove temporary file
          rm raw_host
          
          # Show statistics
          echo "Processed domains: $(wc -l < sophos_web_blocklist.txt)"

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sophos_web_blocklist.txt
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update Sophos blocklist - $(date '+%Y-%m-%d %H:%M:%S') Latvia time"
            git push
            echo "Changes committed and pushed"
          fi
